platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

target 'DemoFlutter' do
  use_frameworks!
  inhibit_all_warnings!

  pod 'AFNetworking', '~> 4.0.0'
  
      flutter_application_path = '/Users/joy/Desktop/flutter-demo/flutter_module'
      load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

      install_all_flutter_pods(flutter_application_path)

  
end
